name: actions

on: [push, pull_request]

jobs:
  sunny-front-test: ...
  sunny-front-release:
    if: ${{ github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/docker' }}  # 1
    runs-on: ubuntu-latest
    needs: sunny-front-test  # 2
    steps:
    - uses: actions/checkout@v2
    - run: npm --prefix sunny-front install
    - run: npm --prefix sunny-front run build
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-shenzhen.aliyuncs.com
        region-id: cn-shenzhen  # 3
        username: "${{ secrets.ALIYUN_USER }}"
        password: "${{ secrets.ALIYUN_PASSWD }}"
    - name: Build Docker Image
      run: bash docker/build-docker-image-sunny-frontend.sh
    - name: Push Docker Image
      run: bash docker/push-docker-image-sunny-frontend.sh
